### ISSUE TITLE
tsc complains about bad import for `../../types/resources/annotation` in `annotation.d.ts`

### ISSUE THREAD

**Issue by jbaiter** [IIIF-Commons/presentation-2-types#1]
```
../node_modules/.pnpm/@iiif+presentation-2@1.0.1_@iiif+presentation-3@1.0.6/node_modules/@iiif/presentation-2/resources/annotation.d.ts:6:34 - error TS2307: Cannot find module '../../types/resources/annotation' or its corresponding type declarations.

import { SpecificResource } from '../../types/resources/annotation';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````
https://github.com/IIIF-Commons/presentation-2-types/blob/main/resources/annotation.d.ts#L6

It seems to me that `SpecificResource` is not included in the `@iiif/presentation-2` module, but is instead part of `@iiif/presentation-3`: https://github.com/IIIF-Commons/presentation-3-types/blob/b6a207ca7ae5d72651363c52e4111738f91dccb4/resources/annotation.d.ts

**Comment by stephenwf** [comment]
Published in `@iiif/presentation-2@v1.0.2` also thanks!
